name = "Red Rose"
license = "MIT"
licenselink = "https://github.com/httpsecure/hugo-theme-red-rose/blob/main/LICENSE"
description = "Hugo Blog Portofolio Dark theme"

# The home page of the theme, where the source can be found.
homepage = "https://github.com/httpsecure/hugo-theme-red-rose"

# If you have a running demo of the theme.
demosite = "https://red-rose.netlify.app/"

tags = ["blog", "portofolio", "dark theme"]
features = ["bootstrap"]


# If the theme has a single author
[author]
    name = "Aziz"
    homepage = "https://github.com/httpsecure"

