[build]
publish = "public"
command = "hugo --minify --gc"

[build.environment]
HUGO_VERSION = "0.98.0"
HUGO_BASEURL = "/"

[[headers]]
for = "/*" 

[headers.values]
Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
X-Content-Type-Options = "nosniff"
X-XSS-Protection = "1; mode=block"
X-Frame-Options = "DENY"
Referrer-Policy = "strict-origin-when-cross-origin"
Cache-Control = "private, max-age=31536000"


